### PR TITLE
Auth test

### PR DESCRIPTION
**Pull request by Jehfkemsy**

### CODE REVIEW

**Comment by Jehfkemsy** [comment]
don't merge it yet...let me check if there's any error with the git conflict commit

**Comment by Tommy2016x** [comment]
Did you make this branch of off master? there's a lot of changes being showed

**Comment by Jehfkemsy** [comment]
yea.... we testing the API with the front-end and some of the authentification stuff failed and i also added the actual contents to the email templates

**Comment by Jehfkemsy** [comment]
i've just tested it tho

**Pull request merged**
